# ===================================================================
# Spring Boot configuration for the "docker-dev" profile.
#
# Ejecuta dentro de Docker Compose (docker-dev/).
# ===================================================================

spring:
  docker:
    compose:
      enabled: false
  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
  cloud:
    consul:
      host: consul
      port: 8500
      config:
        fail-fast: false
        format: yaml
        profile-separator: '-'
      discovery:
        prefer-ip-address: true
    stream:
      kafka:
        binder:
          brokers: kafka:29092
  r2dbc:
    url: r2dbc:postgresql://postgres-scrutiny:5432/tyseScrutinyMicroScrutiny
    username: tyseScrutinyMicroScrutiny
    password:
  liquibase:
    contexts: dev, faker
    url: jdbc:postgresql://postgres-scrutiny:5432/tyseScrutinyMicroScrutiny
    user: tyseScrutinyMicroScrutiny
    password:

logging:
  level:
    ROOT: INFO
    tech.jhipster: INFO
    com.tyse.scrutiny: DEBUG
